apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  labels:
    app: nextjs-eks-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-eks-demo
  template:
    metadata:
      labels:
        app: nextjs-eks-demo
    spec:
      containers:
        - name: nextjs-eks-demo
          image: ghcr.io/<your-username>/nextjs-eks-demo:latest
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_APP_NAME
              value: "NextJS Docker Demo (K8s)"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
