name: Build and Push Docker Image to GHCR

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read      # Read access to repository
      packages: write     # Write access to push image to GHCR

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nextjs-eks-demo:latest
            ghcr.io/${{ github.repository_owner }}/nextjs-eks-demo:${{ github.sha }}