name: Build and Push Docker Image to GHCR

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Convert repo owner to lowercase (important fix!)
      - name: Set lowercase owner name
        id: lowercase
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Step 3: Login to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.lowercase.outputs.owner }}/nextjs-eks-demo:latest
            ghcr.io/${{ steps.lowercase.outputs.owner }}/nextjs-eks-demo:${{ github.sha }}